--1
  CREATE TABLE CLIENTE (
	id_cliente SERIAL PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL,
	apellido VARCHAR(50) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	dni VARCHAR(20) UNIQUE NOT NULL,
	telefono VARCHAR(20),
	fecha_registro DATE DEFAULT CURRENT_TIMESTAMP
  );
